
Rscript -e 'install.packages("igraph", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("lmerTest", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("lme4", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("vegan", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("fields", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("raster", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("bipartite", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("RColorBrewer",repos="http://cran.r-project.org")'
Rscript -e 'install.packages("fossil", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("nimble", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("rgdal", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("maptools", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("sp", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("abind", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("R2jags", repos="http://cran.r-project.org")'
